import "../../public/assets/css/style.css"
import type { Metadata } from "next";
import Script from "next/script";
import StoreProvider from "./StoreProvider";

export const metadata: Metadata = {
    title: "RAGA",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {


    return (
        <html lang="fa" dir="rtl" id="kt_app_body" data-bs-theme="light" data-kt-app-header-fixed="true" data-kt-app-header-fixed-mobile="true" data-kt-app-sidebar-enabled="true" data-kt-app-sidebar-fixed="true" data-kt-app-sidebar-push-header="true" data-kt-app-sidebar-push-toolbar="true" data-kt-app-sidebar-push-footer="true" className="app-default">
            <head>
                <link rel="stylesheet" href="/assets/css/style.bundle.rtl.css" />
                <link rel="stylesheet" href="/assets/plugins/global/plugins.bundle.rtl.css" />
                <link
                    href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
                    rel="stylesheet"
                />
                <Script src="/assets/plugins/global/plugins.bundle.js" strategy="afterInteractive" />
                <Script src="/assets/js/scripts.bundle.js" strategy="afterInteractive" />
            </head>
            <body cz-shortcut-listen="false">
                <StoreProvider>
                    {children}
                </StoreProvider>
            </body>
        </html>
    )
}
