import "../../../public/assets/css/style.css"
import type { Metadata } from "next";
import { routing } from "@/i18n/routing";
import { getMessages, setRequestLocale } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import Script from "next/script";
import StoreProvider from "./StoreProvider";

export const metadata: Metadata = {
    title: "RAGA",
    description: "Generated by create next app",
};

export function generateStaticParams() {
    return routing.locales.map((locale) => ({ locale }));
}

export default async function RootLayout({
    children,
    params
}: Readonly<{
    children: React.ReactNode;
    params: Promise<{ locale: string }>;
}>) {

    const { locale } = await params;
    const message = await getMessages();
    if (!routing.locales.includes(locale as any)) {
        //notFound()
    }

    setRequestLocale(locale);
    const dir = ['fa', 'ar'].includes(locale) ? 'rtl' : 'ltr';

    return (
        <html lang={locale} dir={dir} id="kt_app_body" data-bs-theme="light" data-kt-app-header-fixed="true" data-kt-app-header-fixed-mobile="true" data-kt-app-sidebar-enabled="true" data-kt-app-sidebar-fixed="true" data-kt-app-sidebar-push-header="true" data-kt-app-sidebar-push-toolbar="true" data-kt-app-sidebar-push-footer="true" className="app-default">
            <head>
                {
                    dir === 'rtl' ? (
                        <>
                            <link rel="stylesheet" href="/assets/css/style.bundle.rtl.css" />
                            <link rel="stylesheet" href="/assets/plugins/global/plugins.bundle.rtl.css" />
                        </>
                    ) : (
                        <>
                            <link rel="stylesheet" href="/assets/css/style.bundle.css" />
                            <link rel="stylesheet" href="/assets/plugins/global/plugins.bundle.css" />
                        </>
                    )
                }
                <link
                    href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
                    rel="stylesheet"
                />
                <Script src="/assets/plugins/global/plugins.bundle.js" strategy="beforeInteractive" />
                <Script src="/assets/js/scripts.bundle.js" strategy="beforeInteractive" />
            </head>
            <body cz-shortcut-listen="false">
                <NextIntlClientProvider messages={message}>
                    <StoreProvider>
                        {children}
                    </StoreProvider>
                </NextIntlClientProvider>
            </body>
        </html>
    )
}
